name       : goocanvas
version    : 3.0.0
release    : 10
source     :
    - https://download.gnome.org/sources/goocanvas/3.0/goocanvas-3.0.0.tar.xz : 670a7557fe185c2703a14a07506156eceb7cea3b4bf75076a573f34ac52b401a
homepage   : https://gitlab.gnome.org/GNOME/goocanvas
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : GTK+ canvas widget
description: |
    GooCanvas is a canvas widget for GTK+ that uses the cairo 2D library for drawing.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
