name       : goocanvas
version    : 2.0.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/goocanvas/2.0/goocanvas-2.0.2.tar.xz : f20e5fbef8d1a2633033edbd886dd13146a1b948d1813a9c353a80a29295d1d0
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : GTK+ canvas widget
description: |
    GooCanvas is a canvas widget for GTK+ that uses the cairo 2D library for drawing.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
