name       : goocanvas
version    : 2.0.4
release    : 5
source     :
    - https://download.gnome.org/sources/goocanvas/2.0/goocanvas-2.0.4.tar.xz : c728e2b7d4425ae81b54e1e07a3d3c8a4bd6377a63cffa43006045bceaa92e90
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : GTK+ canvas widget
description: |
    GooCanvas is a canvas widget for GTK+ that uses the cairo 2D library for drawing.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
